server.port: 8090
spring.datasource.password: drones
spring.datasource.username: drones
spring.datasource.url: jdbc:postgresql://localhost/drones-app
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

#logging:
#  level:
#    org.hibernate: DEBUG


