server.port: 8090
spring.datasource.password: drones
spring.datasource.username: drones
spring.datasource.url: jdbc:postgresql://localhost/drones-app
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        generate_statistics: true

logging:
  level:
    org.hibernate: DEBUG
